test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python-dev python-pip libffi-dev libssl-dev libgpgme11-dev libgit2-dev make
  - pip install -r development.txt
  - make test

  variables:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    PYTHONSTARTUP: .startup.py
