- name: "[base] installing dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ntp
    - nginx
    - upstart
    - telnet
    - git
    - vim
    - curl
    - git-svn
    - ca-certificates
    - build-essential
    - python
    - htop
    - subversion
    - wget
    - pkg-config
    - libffi-dev
    - libssl-dev
    - libgcrypt11-dev
    - libudev-dev
    - libev-dev
    - libnss3
    - libgpg-error-dev
    - libgpgme11-dev
    - python-gpgme
    - redis-server
    - redis-tools

- name: "[base] starting ntpd"
  service: name=ntp state=started enabled=yes
