- include: base.yml
- include: ssh.yml
- include: ssl.yml
- include: nginx.yml
- include: wsgi.yml

- name: "ensure main permissions"
  shell: chown -R oldspeak:oldspeak-services "{{ item }}"
  with_items:
    - /srv
    - /srv/mail
    - /srv/open-source
    - /srv/private-data
    - /srv/public-data
    - /srv/src
    - /srv/ssh
    - /srv/uploads

- name: "ensure service-wide group permissions"
  shell: chown -R oldspeak:oldspeak-services "{{ item }}"
  with_items:
    - /srv/log
    - /srv/open-source
    - /srv/public-data
    - /srv/src
    - /srv/src/static

- name: "www-data owner of /srv/src/static"
  shell: chown -R www-data:oldspeak-services /srv/src/static

- name: "fix permissions of dirs"
  shell: find /srv -type d -exec chmod 755 {} \;

- name: restart application
  service: name=python-app state=restarted

- name: restart nginx
  service: name=nginx state=restarted
