- name: setup persistence user
  mysql_db: name="{{ oldspeak_mysql_db }}" state=present

- name: setup persistence user
  mysql_user: name="{{ oldspeak_mysql_user }}" password="{{ oldspeak_mysql_password }}" priv=*.*:ALL state=present

- name: run migrations
  shell: "{{ venv_path }}/bin/alembic -c /srv/src/alembic.ini upgrade head"
  args:
    chdir: /srv/src
