- name: ensure wsgi folder
  file: path=/srv/wsgi state=directory

# - name: prepare wsgi.py file
#   template: src=python-app.upstart
#     dest="/srv/src/oldspeak_wsgi_server.py"
#     owner=oldspeak group=oldspeak-services mode=660
#   notify: restart python-app

- name: install python-app upstart script with gunicorn
  template: src=python-app.upstart
    dest="/etc/init/python-app.conf"
    owner=root group=root mode=644
  notify: restart python-app
